### ISSUE TITLE
UpdatedMedia not used/implemented

### ISSUE THREAD

**Issue by dacox** [shutterstock/public-api-sdk-generator#45]
It seems like the `List of updated <asset_type>` API endpoints are not part of `openapi.json` (https://developers.shutterstock.com/images/apis/get/images/updated)
I see generated models for `UpdatedMediaDataList` and `UpdatedMedia`, however, they do not seem to be used anywhere.

**Comment by jacobemerick** [comment]
Hey @dacox, great call. We're working on exposing that endpoint via the SDK and our docs now, should be out in the next few days.

**Comment by jacobemerick** [comment]
Hi @dacox - version 1.0.5 of the sdk has updatedImage functionality. Let us know if you have any questions! https://www.npmjs.com/package/shutterstock-api/v/1.0.5
